version: "3"

services:  
  elasticvue:
    image: cars10/elasticvue
    ports:
      - "8080:8080"    
  
  redisinsight:
    #redis web client (http://localhost:8010/)
    image: "redislabs/redisinsight:latest"
    ports:
      - "8010:8001"

  kibana:
    #client http://magento-lic.local:5601/app/kibana
    image: kibana:7.8.1
    volumes:
      - ./images/kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
      
  #logstash:
  #  image: logstash:7.8.1
  #  #container_name: elk-logstash
  #  #restart: unless-stopped
  #  volumes:
  #    - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
  #  depends_on:
  #    - elasticsearch
  #  #networks:
  #  #  - elk-network
    
  #filebeat:
  #  image: elastic/filebeat:7.8.1
  #  #restart: unless-stopped
  #  depends_on:
  #    - elasticsearch
  #  volumes:
  #    - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #    - ./logs/:/logs/
  #  #networks:
  #  #  - elk-network  
      
  
  #k6:
  #  #image: grafana/k6
  #  build: images/k6
  #  volumes:
  #    - ./src-k6:/var/www/html:cached 