version: "3"

services:  
  elasticvue:
    image: cars10/elasticvue
    ports:
      - "8080:8080"
  
  redisinsight:
    #redis web client (http://localhost:8010/)
    image: "redislabs/redisinsight:latest"
    ports:
      - "8010:8001"

  kibana:
    #client http://magento-lic.local:5601/app/kibana
    image: kibana:7.8.1
    volumes:
      - ./images/kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601  
  
  #k6:
  #  #image: grafana/k6
  #  build: images/k6
  #  volumes:
  #    - ./src-k6:/var/www/html:cached 