FROM grafana/k6

#COPY ./bin/start.sh /usr/bin/start.sh
#
#RUN chmod +x /usr/bin/start.sh
#
#ARG APP_USER_ID
#ENV APP_USER_ID=${APP_USER_ID}
#
#RUN usermod -u $APP_USER_ID node;
#
#WORKDIR /var/www/current
#
#USER node
#
#CMD ["bash"]
